services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bank
    volumes:
      - ./src/db/:/docker-entrypoint-initdb.d
    ports:
      # - 5432:5432
      - 12456:5432
    restart: always
